### ISSUE TITLE
Parsing Error for Bread crumb navigation _ W3c Nu Validator

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#100]
![image](https://cloud.githubusercontent.com/assets/15111528/10966918/ef007a2a-840a-11e5-87de-069287def0cf.png)
![image](https://cloud.githubusercontent.com/assets/15111528/10966937/0fb22412-840b-11e5-9107-62a50a5a2b1c.png)

**Comment by mr-bobz** [comment]
@anmolpatel, try moving the role=region to the child div from h1.

**Comment by anmolpatel** [comment]
fixed!
added a jQuery to remove role from h1 and add it to div tag

**Comment by HerinHentry** [comment]
![image](https://cloud.githubusercontent.com/assets/15111528/11062429/062eab30-8803-11e5-9092-3f01aae71a4a.png)

**Comment by anmolpatel** [comment]
fixed by bobby to this ->
<div id="breadcrumbs" role="region" aria-label="breadcrumb navigation">

please re-test

**Comment by HerinHentry** [comment]
Issue still persists. Not able to identify the source of this issue.
Did some googling and it suggests looking at the code to see if any other element has been left with out closing it. Will leave this for now until other major issues are resolved.
http://help.simplytestable.com/errors/html-validation/element-x-not-allowed-as-child-of-element-y-in-this-context-suppressing-further-errors-from-this-subtree/element-div-not-allowed-as-child-of-element-h2-in-this-context-suppressing-further-errors-from-this-subtree/

**Comment by anmolpatel** [comment]
why do we have breadcrumbs as h1 in the first place ?
aren't breadcrumbs just meant to be navigation aid, 

Can we can use <p ="nav-aid"><div id="breadcrumbs"> </div></p> and modify than further modify the size as needed ?

**Comment by mr-bobz** [comment]
Looks like you pasted some html and it was removed by github.

We need an h1 as page title for every page. We didn't want to repeat since breadcrumb also shows the same, especially for Home page!

**Comment by anmolpatel** [comment]
im not sure what you mean there, haven't added any html related to breadcrumb

**Comment by mr-bobz** [comment]
should be ok now, I guess.
