### ISSUE TITLE
Remove the word **icon** from the 3 entry point images in Home page.

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#102]
No need to mention the word **icon** in the images. Screen readers do announce this as **graphic** link.

<...img src="/wp-content/uploads/2015/11/member.png" alt="**member icon**" width="48" height="48" /><br />
<...img src="/wp-content/uploads/2015/10/volunteer.png" alt="**volunteer icon**" width="48" height="48" /><br />
<...img src="/wp-content/uploads/2015/10/support.png" alt="**support icon**" width="48" height="48" />

**Comment by HerinHentry** [comment]
This can be fixed with the new images from @manuum

**Comment by HerinHentry** [comment]
These are decorative icons. Alt text =" " is best practice.
![image](https://cloud.githubusercontent.com/assets/15111528/10995893/6c3cbe62-84d4-11e5-9c1d-5c742a38e074.png)

**Comment by mr-bobz** [comment]
Done

**Comment by HerinHentry** [comment]
Can be closed as this is fixed.

**Comment by christosptr** [comment]
@HerinHentry so can I close this one?
