### ISSUE TITLE
<br> element in the middle of the anchor element is confusing for Braille users

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#103]
I am testing the website for Braille users with Text only browser Lynx. The 3 entry points have line break inbetween and hence displayed in 2 line.

![image](https://cloud.githubusercontent.com/assets/15111528/10986741/cb110276-8480-11e5-8b83-fe2b1ccd218b.png)

Code : <...a href="/services/membership/"><span class="member"><...img src="/wp-content/uploads/2015/11/member.png" alt="member icon" width="48" height="48" /><...br />
Become<...br /><...em>Member<.../em><.../span><.../a>

Fix : Using CSS to fix this might be an option. Did some Analysis and found an easy fix. Can we try this please?

![image](https://cloud.githubusercontent.com/assets/15111528/10986848/a3691c3a-8481-11e5-90e8-9066cff6117f.png)

**Comment by mr-bobz** [comment]
This wouldn't be an issue when we use images from @manuum. So no point fixing now.

**Comment by HerinHentry** [comment]
Excellent! Thank you.

**Comment by HerinHentry** [comment]
Issue can be closed as images are used for entry point now.
