### ISSUE TITLE
Youtube video _ Intro needed

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#104]
While testing with screen reader, after the Do I qualify section, NVDA reads the title "TALA promotional video by pitch productions". But, it would be good to give a little blurb (one liner as text before the video to day what it is about & mention the youtube is caption supported).

For example 
A <..H2> Pitch Productions _ Nicole Elmer & Blair Dancy talks about TALA services on this video
<..em> This video is captioned.

This also supports the users to easily identify the accessibility feature that is supported.
**Advantage**: As it has a H2, non-sighted users identify there is a video on the page.

@christosptr : What are your thoughts on this? 
@mr-bobz : I have also commented on #42 as the updates have made the played inaccessible.

**Comment by mr-bobz** [comment]
Added, please check

**Comment by HerinHentry** [comment]
Thanks. Looking good. But, a small suggestion...
**Nicole Elmer from Pitch Productions & Blair Dancy from TALA talk about our services in this video**
Will probably be the proper heading as it says who these people are...
@mr-bobz Do you think this will be good?

**Comment by mr-bobz** [comment]
Would be too long for a heading (h2), I think it is too much details

**Comment by HerinHentry** [comment]
How about TALA_promo Video as a heading and these lines go as a <..p> below?

**Comment by mr-bobz** [comment]
Anyone should be able to make above change

**Comment by HerinHentry** [comment]
@christosptr Can you please change as suggested?

**Comment by christosptr** [comment]
I tried to change it but when I do the text is not style correctly
Will give it another go now

**Comment by christosptr** [comment]
@HerinHentry Just to clarify you want the <..em> This video is captioned.
to be after the video header 
<..H2> Pitch Productions _ Nicole Elmer & Blair Dancy talks about TALA services on this video
and before the video player?

**Comment by HerinHentry** [comment]
Hi @christosptr I think it's better to include all these details before the video.The users need to informed about it as the DOM receives info based on code order.

<..H2> Pitch Productions _ TALA Promo video
<...p> Nicole Elmer from Pitch Productions & Blair Dancy from TALA talk about TALA services in this video
<..em> Note: This video is captioned

**Comment by christosptr** [comment]
Done the change with the <..em> Note: This video is captioned

been between the header and the video player
@HerinHentry can you please close if you okay with it?

**Comment by HerinHentry** [comment]
Looks good. Issue can be closed.
