### ISSUE TITLE
Sponsor Logos need a background border to make it more clear & resize to fit into singleline.

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#105]
![image](https://cloud.githubusercontent.com/assets/15111528/10990452/642d8300-84a7-11e5-9e3f-db7998812904.png)

**Comment by ruchitamanuja** [comment]
@HerinHentry 
I have recreated the logos and added them on the homepage. Please have a look and let me know if they look ok. 
![image](https://cloud.githubusercontent.com/assets/15117771/11015516/acadc59a-85b5-11e5-99ce-36ec79bdfec8.png)

**Comment by HerinHentry** [comment]
![image](https://cloud.githubusercontent.com/assets/15111528/11020522/16d0f6b2-8675-11e5-9326-0c2d70b05c7e.png)

Looks good. Closing the issue.
Thanks
