### ISSUE TITLE
Reduce spacing to fit the content into same sized boxes

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#106]
![image](https://cloud.githubusercontent.com/assets/15111528/10990495/f6f2f12a-84a7-11e5-8fc8-24253c40f206.png)

**Comment by mr-bobz** [comment]
Reducing space won't fix it. We need to size the boxes according to the tallest one. I will check

**Comment by mr-bobz** [comment]
Fixed via adding a jQuery module in custom.js.

**Comment by HerinHentry** [comment]
Issue fixed.
