### ISSUE TITLE
TALA Promotional Video by pitch productions on top of the youtube player _opens in new window

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#109]
![image](https://cloud.githubusercontent.com/assets/15111528/10991153/f5b7961a-84ae-11e5-9307-80767025beff.png)

This opens in new window. But, not announced.

**Comment by mr-bobz** [comment]
I have disabled that in youtube via some params. But still there is a 'Watch on You Tube' control at the bottom right corner. Can't remove it as it comes from youtube.

**Comment by HerinHentry** [comment]
The full screen is currently disabled. clicking on this brings this page.
https://support.google.com/youtube/answer/6276924
If we support Text resize, I think we should also support full screen view. Is this disabled by youtube or by our code? Is there any way to fix this?

**Comment by mr-bobz** [comment]
Not our code, @christosptr pls check video settings on youtube. Seems you may have disabled full screen when embedded!

**Comment by christosptr** [comment]
will have a look

**Comment by christosptr** [comment]
@mr-bobz and @HerinHentry Hi guys the full screen works on firefox but not on Chrome or IE

Herin can you please check this at your end for IE and Chrome

**Comment by HerinHentry** [comment]
Full screen is  working on IE for me. Not working on Firefox and Chrome.
Looks like browser issues. I also checked the browser permissions. Doesn't seem to work.
Alternatively, If this video opens up in Youtube as full screen, then we can provide a link to youtube.
Please advise.

**Comment by christosptr** [comment]
I am not sure about this one :(

**Comment by christosptr** [comment]
@HerinHentry and @mr-bobz  

This is what I have found for this issues
https://support.google.com/youtube/answer/6276924

It looks like this is an issues with the browser and not the settings on YouTube.

Can I close this issues

**Comment by HerinHentry** [comment]
@christosptr Yes. We can close this issue. I am closing now.
