### ISSUE TITLE
Parsing Error _ FAQ page

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#110]
![image](https://cloud.githubusercontent.com/assets/15111528/10991346/8f163518-84b0-11e5-83f2-4235b9d225e5.png)

![image](https://cloud.githubusercontent.com/assets/15111528/10991368/bd3da426-84b0-11e5-98f5-093073148e98.png)

![image](https://cloud.githubusercontent.com/assets/15111528/10991371/cf23751c-84b0-11e5-9c96-41632c177f21.png)

**Comment by anmolpatel** [comment]
checked on achecker, issue cannot be replicated
can close this

**Comment by HerinHentry** [comment]
Issue resolved with the tabs. Closing this off
