### ISSUE TITLE
Disclaimer text (in yellow background) on Home page & whatwedo page needs to be included in tabbing

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#111]
http://talarts.knowbility.org/
http://talarts.knowbility.org/services/whatwedo/

As these are the very important messages, these needs tab index to be set. This will add a point to exemplary efforts.

**Comment by mr-bobz** [comment]
Done

**Comment by HerinHentry** [comment]
Excellent! works now. Closing issue!
