### ISSUE TITLE
Is it possible to set the Post Titles as H3?

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#112]
Given below is the outline of the Events page. The Posts need to be H3 under the Upcoming Events and Past Events.

![image](https://cloud.githubusercontent.com/assets/15111528/10991562/74c7b608-84b2-11e5-8cd8-7cb1844f3a7b.png)

**Comment by mr-bobz** [comment]
Changed Upcoming Events to h2 and post titles to h3

**Comment by HerinHentry** [comment]
This structure doesn't seem to properly fit in...
Upcoming events & past events should be under Events. Not the same level. Can we please change?
![image](https://cloud.githubusercontent.com/assets/15111528/11000362/665f5434-84f5-11e5-8140-de6d1a667aa9.png)

**Comment by mr-bobz** [comment]
<H2>Events</H2> was hidden. Removed now.

**Comment by christosptr** [comment]
I have verified the events page and it looks ok now. @HerinHentry can I close it?

**Comment by HerinHentry** [comment]
If the upcoming events list is H3, other past events should also be displayed as H3.
Can we modify that? User will expect the same behaviour in both lists.

![image](https://cloud.githubusercontent.com/assets/15111528/11001818/79166e16-84fd-11e5-9411-eb6f3f7a1472.png)
