### ISSUE TITLE
Decorative images have anchor & href.

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#114]
This image is a decorative image only. This does not need an alt text & href. Current alt text is set to " " " " (4 quotes). Change to 2 quotes.

**http://talarts.knowbility.org/the-austin-chapter-of-the-texas-society-of-cpas-presents-nonprofit-financial-class/**

![image](https://cloud.githubusercontent.com/assets/15111528/10996272/c44a1890-84d7-11e5-94fd-32f9a8142ae2.png)

<...a href="/wp-content/uploads/2015/10/cpa_logo-300x64.png"><...img width="300" height="64" class="alignnone size-medium wp-image-649" alt='" "' src="/wp-content/uploads/2015/10/cpa_logo-300x64-300x64.png"><.../a>

**http://talarts.knowbility.org/october-estate-planning-for-artists/**

<...img width="300" height="186" class="alignnone size-medium wp-image-334" alt="" "" src="/wp-content/uploads/2015/10/October-is-Estate-Planning-Month-300x186-300x186.jpg">

![image](https://cloud.githubusercontent.com/assets/15111528/10996380/918a3b78-84d8-11e5-9361-6906cd22eea7.png)

**http://talarts.knowbility.org/tala-dallas-week/**

![image](https://cloud.githubusercontent.com/assets/15111528/10996434/de6a2f3e-84d8-11e5-8c6f-82e9797d5cf6.png)

**Comment by ruchitamanuja** [comment]
Fixed.

**Comment by HerinHentry** [comment]
Issue can be closed.
