### ISSUE TITLE
Broken link http://talarts.knowbility.org/support/donate/ in Home page entry point Support

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#115]

**Comment by mr-bobz** [comment]
What is broken there? Page loads fine for me

**Comment by HerinHentry** [comment]
Donate is no longer a child page of Support. Looks like it's part of Home now.

**Comment by mr-bobz** [comment]
Whoever changed it should make sure to update all links too :)

**Comment by HerinHentry** [comment]
Not sure.. Why is this changed?

**Comment by mr-bobz** [comment]
Fixed

**Comment by HerinHentry** [comment]
Works. Can be closed.
