### ISSUE TITLE
Home page has 2 H1 tags

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#116]
I am not sure if this is a duplicate issue that is being tracked with another defect. But, raising this to track.

1) <...h1 role="region" aria-label="breadcrumb navigation"><...div id="breadcrumbs"><span xmlns:v="http://rdf.data-vocabulary.org/#"><...strong class="breadcrumb_last">Home

2) <...header class="entry-header">
            <...h1 class="entry-title" itemprop="headline">Home</h1>
<.../header>

**7.Headings for navigation (10 points).**
 Use headings to identify sections and subsections of content. Within the landmark region you must have consistent heading levels. Each page should have **at least one H1** heading and heading levels should not skip (H2 then H4). Each incorrect use of headings is an error.

**Using one h1 tag supports SEO as per recommendations from lot of websites**

**Comment by mr-bobz** [comment]
Fixed

**Comment by HerinHentry** [comment]
We cannot have 2 tags for the same heading text. one says H1 and the other says H2. Can you please change this? Do we need to have 2 displayed?

![image](https://cloud.githubusercontent.com/assets/15111528/11000302/053f5e60-84f5-11e5-801a-de18d784ec7c.png)

**Comment by mr-bobz** [comment]
The second h2 tag is not displayed! I will see whether it could be avoided altogether.

**Comment by mr-bobz** [comment]
Fixed

**Comment by HerinHentry** [comment]
Will check with screen reader.

**Comment by HerinHentry** [comment]
@mr-bobz Only one Home announced in NVDA
breadcrumb navigation region 
Home
If we cannot fix this we can check with JAWS and close the issue.
Please assign to @christosptr to check with Jaws.

**Comment by mr-bobz** [comment]
What needs to be fixed now? You need both Home?

**Comment by mr-bobz** [comment]
Second 'Home' was hidden already, not generated now.

**Comment by HerinHentry** [comment]
Excellent.Can be closed.
