### ISSUE TITLE
Link to underline on focus

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#117]
Note from judging from **point 8 : additional differentiation such as underlining is provided when the link is hovered over or receives focus.**

Read more on TALA Assistance... & Read more on TALA mission... These 2 links initially have the underlines and the underlines are removed when it receives focus. This is contradicting the requirement.

Please make the link to underline on hover / receive focus.

**Comment by mr-bobz** [comment]
done

**Comment by HerinHentry** [comment]
Excellent! Works now. Can be closed.
