### ISSUE TITLE
24. Language  _ Pro bono

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#119]
1. Language Changes. The human language of each passage or phrase in the content can be programmatically determined, except for proper names, technical terms, words of indeterminate language, and words or phrases that have become part of the vernacular of the immediately surrounding text. Identify language changes within a page. Any failure is score of 0.

Pro-bono is a Latin word (https://en.wikipedia.org/wiki/Pro_bono).

This occurs in 5 places in the website.
Can we use Language of parts for this to score the points? (5 points)

**Pages**
http://talarts.knowbility.org/about/mission/
http://talarts.knowbility.org/about/faq/
http://talarts.knowbility.org/services/do-i-qualify/
http://talarts.knowbility.org/support/volunteer/
http://talarts.knowbility.org/about/boardandstaff/

**The names in the BoardandStaff** are another language specific ones.

**Comment by mr-bobz** [comment]
I'm not sure what needs to be done here, perhaps @ruchitamanuja would be the right person?

**Comment by HerinHentry** [comment]
@christosptr : What do you think about this? Normally this is applicable to longer poems / phrases.

Can you please check this?
http://www.w3.org/TR/2015/NOTE-WCAG20-TECHS-20150226/H58.html

**Comment by christosptr** [comment]
If the word is now used in English then this does not require to have the Language Changes.

We should use this when sentences are written in characters other than Elglish 
eg
If a name is written in Greek eg Χρήστος then we will need to do this

Do we have any cases like this one in the TALA website?

**Comment by HerinHentry** [comment]
Excellent! Issue can be closed.
