### ISSUE TITLE
Sitemap _ Heading structure not present

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#121]
Site map do not have a heading structure. Everything is a link.
@christosptr : Will this be an issue?

**Comment by christosptr** [comment]
I do not think this will be a problem with the site map

**Comment by HerinHentry** [comment]
@christosptr : The sitemap does not display the posts (Past Events & upcoming events). Will this be an issue?

**Comment by christosptr** [comment]
Generally the sitemap is to show the structure of the website
Not sure about this? It can go either way based on each judge.
It they were simply posts/comments you do not want that to show on the website structure but we post events which are important information.

**Comment by HerinHentry** [comment]
Can we please check with steve to check accessibility of site map?

Sent from my phone

<div>-------- Original message --------</div><div>From: Christos Petrou notifications@github.com </div><div>Date:07/11/2015  11:59 AM  (GMT+10:00) </div><div>To: mr-bobz/talarts talarts@noreply.github.com </div><div>Cc: HerinHentry herinnisha@gmail.com </div><div>Subject: Re: [talarts] Sitemap _ Heading structure not present (#121) </div><div>
</div>Generally the sitemap is to show the structure of the website
Not sure about this? It can go either way based on each judge.
It they were simply posts/comments you do not want that to show on the website structure but we post events which are important information.

**Comment by mr-bobz** [comment]
Added events also to Sitemap

**Comment by christosptr** [comment]
great I have tested it and is there now closing defect
