### ISSUE TITLE
FAQ Page_Accordion does not support Keyboard navigation

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#122]
When The keyboard focus is on 
**How can I get assistance from TALA ?**
Tabbing sets the focus to the facebook icon. It does not go to the next levels of FAQ Accordion.

**Comment by christosptr** [comment]
you need to use the arrow keys
the accessibility page also has instruction on how to use it

Cheers Christos
Send from my mobile device

**Comment by HerinHentry** [comment]
@christosptr , The Navigate with in the Accordion   > Left and right Or Up and down arrow keys is not working for me. The Left / right also goes to the next level heading.
The arrow keys are only working for the 2nd accordion.

Tab into Accordion 1 header > Use down arrow (Goes to Accordion 2 header) > Use Enter (Accordion opens) > Use Tab (Enters into accordion 2 content) > Tab again... (goes to facebook icon).
Accordion 3 & 4 are not getting focussed after the arrow key is used.

But, if I am tabbing straight into the 3rd header, it gets focus. But, the internal content does not get focus.

**Comment by christosptr** [comment]
are you still having a problem. I have retested it with Chrome and firefox with and without JAWS and is fine for me

**Comment by HerinHentry** [comment]
@christosptr It's still not working for me. I think I found the issue.

The ARIA roles are not nested in the right order. Hence the issue.
The Tablist role must include child elements with role="tab".
Currently, Tabpanel is nested with in the role tab. Hence the keyboard navigation is not working as expected.

Please see below for the demo of Tab. (This can be used for Accordion as well)

http://whatsock.com/tsg/Coding%20Arena/ARIA%20and%20Non-ARIA%20Tabs/ARIA%20Tabs%20(Internal%20Content)/demo.htm

**nesting order**
role="tablist" 
  role =  "tab"

Tabpanel is a container for the resources associated with a Tab, where each Tab is contained in a Tablist. (To ensure an accessible reading order for screen reader users, the Tabpanel element should not be a child of Tablist.)

The aria-labelledby attribute should be set on the role="tabpanel" element to reference the ID of the associated Tab element when expanded. The aria-hidden attribute may be used to show or hide associated Tabpanels.

Only one Tabpanel associated with a Tablist can be expanded at the same time. When one Tabpanel is expanded, the previously expanded Tabpanel becomes collapsed (its aria-hidden attribute becomes "true").

**Comment by christosptr** [comment]
I will ask steve for this one as well

**Comment by christosptr** [comment]
Steve have given us a sample solution on Slack will find the link and post it here as well

**Comment by HerinHentry** [comment]
@christosptr , Can you please advise on this?

**Comment by christosptr** [comment]
In NVDA you need to press Esc and then down arrow

**Comment by HerinHentry** [comment]
Excellent!
