### ISSUE TITLE
Donation Page check boxes after the label (cognitive)

### ISSUE THREAD

**Issue by christosptr** [mr-bobz/talarts#123]
Hi @anmolpatel 

Can you please change the check boxes to be first 

Also I still issues with the donation page: For example the name is not announced.
Are you still working on this or have you finish the implementation?

**Comment by christosptr** [comment]
![image](https://cloud.githubusercontent.com/assets/5661003/11013406/980600c6-8560-11e5-9e74-0ec9b1e4aef8.png)

**Comment by anmolpatel** [comment]
fixed! 
was only a temporary change

**Comment by anmolpatel** [comment]
@christosptr

**Comment by christosptr** [comment]
ok

**Comment by christosptr** [comment]
thanks @anmolpatel
