### ISSUE TITLE
Accessibility page _ Heading structure issue

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#124]
The whole table is embedded in the H3 tag.
![image](https://cloud.githubusercontent.com/assets/15111528/11013442/153385e0-8562-11e5-941f-ebc4ed3909bc.png)

**Comment by christosptr** [comment]
@HerinHentry 
I do not see a table having a h3. Can you please check again

**Comment by HerinHentry** [comment]
![image](https://cloud.githubusercontent.com/assets/15111528/11015190/72895738-85a8-11e5-8388-14713ebb4951.png)
Looks like a H3 nesting issue earlier. Issue has been resolved & can be closed.
