### ISSUE TITLE
Accessibility page _ Two different font sizes used in the page

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#125]
http://talarts.knowbility.org/footer/accessibility/
![image](https://cloud.githubusercontent.com/assets/15111528/11013457/ac3718a8-8562-11e5-9904-1f2f52771ae5.png)

**Comment by ruchitamanuja** [comment]
h3 tag was incorrectly used. Fixed to have a close tag '/h3' which was missing

**Comment by HerinHentry** [comment]
Excellent! Issue can be closed.
