### ISSUE TITLE
Accessibility page _ A little blub needed before the page as an intro for the users

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#126]
Please check the accessibility page online from different organisations (Coles for example), and provide a little blurb before the tables.

**Also please change the heading to Menu Navigation, FAQ to FAQ Page_ Tab Navigation**

![image](https://cloud.githubusercontent.com/assets/15111528/11013465/deb6f0aa-8562-11e5-9a89-cb3b7701ccbb.png)

**Comment by christosptr** [comment]
@herin I have made some changes can you please have a look and let me know what you think

**Comment by christosptr** [comment]
@ruchitamanuja @manuum 
Hi guys can you also have a look at the accessibility page and tell me what you think

Cheers
Chris

**Comment by HerinHentry** [comment]
@christosptr : The page content looks good and logical now.

For NVDA + Firefox,

**Comment by HerinHentry** [comment]
@christosptr : The accessibility page looks more logical now.
I recomment to close this issue.

@ruchitamanuja , @manuum  : I am closing this issue to clear the defects. Please reopen if you have any improvement suggestions.
