### ISSUE TITLE
Titles are inconsistent in menu items

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#127]
**This has proper title set**
<...a title="TALA | Events" href="/events/">Events<.../a>

**The menu says board and staff and title says about us**
<...a tabindex="-1" title="**TALA | About Us**" href="/about/boardandstaff/">**Board and Staff**<.../a>

**This menu items and every other menu item does not have a title set**
<...a tabindex="-1" href="/services/whatwedo/">What we do?<.../a>

Can you please check all the menu items and make sure the menu item titles and the page titles match?

**Comment by ruchitamanuja** [comment]
@HerinHentry 
I have added the titles to the menu items. But do we need the "TALA | " prefix for them ? Or should I just remove them and have e.g Events?

**Comment by ruchitamanuja** [comment]
@HerinHentry 
Am I removing the Prefix here??

**Comment by HerinHentry** [comment]
Yes please.

**Comment by ruchitamanuja** [comment]
@HerinHentry 
I have gone and removed the TALA | for the titles but this is now not showing the titles at all for the menus. It works only if put TALA | or anything else before the name.  I have left Events menu with TALA| so you can have a look at it. 
@mr-bobz : Could you please advise , if something needs to be done for this to come across? I found this if it helps : https://wordpress.org/support/topic/title-attribute-in-menu-not-working

![image](https://cloud.githubusercontent.com/assets/15117771/11015378/ffa70ae0-85b0-11e5-978a-ee714defe32a.png)

**Comment by mr-bobz** [comment]
The Title is auto generated and set by the SEO plugin. It is in this format - <Site Title> | <Page Title>

eg: TALA | Events

So just make sure the pages have proper title set.

**Comment by mr-bobz** [comment]
Use 'Quick Edit' in page list to quickly verify and change titles

**Comment by mr-bobz** [comment]
I see that you are referring to menu items. How are we setting title for that? In the menu editor I see only label. And as far as I know links don't need a title when there is a label (link text).
https://silktide.com/i-thought-title-text-improved-accessibility-i-was-wrong/

**Comment by mr-bobz** [comment]
Never mind, found that in customizer you can set a title. Removing for Events also.

**Comment by HerinHentry** [comment]
@mr-bobz . Closing this issue. Thanks
