### ISSUE TITLE
Social media icons _ Youtube should open in a new page (set target blank)

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#128]
Twitter & Facebook opens in a new window. But, youtube is an external site and it opens in the same window.
**As well as please set titles to announce they are external links**
![image](https://cloud.githubusercontent.com/assets/15111528/11013492/3f720ac8-8564-11e5-85a2-7dbdee484b1e.png)

**Comment by mr-bobz** [comment]
Above is not custom code, it comes from Social Menu. Added external site info. Removing YouTube since it doesn't open in new window (looks like a bug)!!

**Comment by HerinHentry** [comment]
Youtube link has been removed. Issue can be closed.
