### ISSUE TITLE
mailto:info@talarts.org : Clarification needed

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#129]
Hi @christosptr , the mail to opens up the outlook / other email client configured on the site. Should this be announced as open in new window?

**Comment by christosptr** [comment]
I think this is okay. Users know that they will be using their own mail software. However we could add an aria-label to say this. I will need to check it

**Comment by HerinHentry** [comment]
Thank you @christosptr . I will leave this issue open to follow up with Steve. Assigning it back to you for adding to your to follow up list.

**Comment by christosptr** [comment]
ok now worries

**Comment by christosptr** [comment]
message send to steve on Slack

**Comment by christosptr** [comment]
text should say "opens in default Email client"

**Comment by mr-bobz** [comment]
added title and aria-label
