### ISSUE TITLE
Footer _ Knowbility logo & modified date need to be separated by a div as they display in one line on IE.

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#130]
![image](https://cloud.githubusercontent.com/assets/15111528/11013531/74bcd73e-8565-11e5-8761-5e4a809c37f3.png)

![image](https://cloud.githubusercontent.com/assets/15111528/11013533/81720c24-8565-11e5-8ae8-b312836b88a7.png)

**Comment by ruchitamanuja** [comment]
@HerinHentry  Can you please try again i added a div. Also it was working fine on my IE even before I did any changes to it. But I am on Edge maybe that is why. 
![image](https://cloud.githubusercontent.com/assets/15117771/11014403/9ba18d4a-8588-11e5-96b0-f61783d01082.png)

**Comment by HerinHentry** [comment]
Issue can be closed.
