### ISSUE TITLE
H28: Providing definitions for abbreviations by using the abbr element

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#131]
TALA is an Abbreviation. As per WCAG2.0 we have this guideline. Are we supposed to use this? If thats the case should we use in Home page alone?

It's not part of the scoring criteria . But, we can include this in the judgement form.

H28: Providing definitions for abbreviations by using the abbr element

<...p>Welcome to the <...abbr title="World Wide Web">WWW<.../abbr>!<.../p>

**Comment by christosptr** [comment]
Yes this is a very good point who can take this ?

**Comment by christosptr** [comment]
I will see if i can make the change
