### ISSUE TITLE
AVT3 Header need the aria-label removed

### ISSUE THREAD

**Issue by christosptr** [mr-bobz/talarts#132]
JAWS announce too much information and is confusing and unclear 

Actual Code
<header itemtype="http://schema.org/WPHeader" itemscope="" aria-label="page banner" role="banner" class="site-header" id="masthead">

Solution
<header itemtype="http://schema.org/WPHeader" itemscope="" role="banner" class="site-header" id="masthead">

**Comment by mr-bobz** [comment]
Done

**Comment by christosptr** [comment]
Verified
