### ISSUE TITLE
The address in the footer need the address tag

### ISSUE THREAD

**Issue by christosptr** [mr-bobz/talarts#134]
Current HTML
<div id="panel-w563b37a3b87c0-0-0-0" class="so-panel widget widget_black-studio-tinymce widget_black_studio_tinymce panel-first-child"><div class="textwidget"><p style="text-align: left;">TALA, PO Box 144722, Austin, TX 78714</p>

<p style="text-align: left;">Phone 1: 512.459.8252<br> Phone 2: 800.526.8252<br> Fax: 512.247.2538<br> Email: <a href="mailto:info@talarts.org">info@talarts.org</a></p>

</div>

Can we change the div to address tag

Suggested solution
<address id="panel-w563b37a3b87c0-0-0-0" class="so-panel widget widget_black-studio-tinymce widget_black_studio_tinymce panel-first-child"><div class="textwidget"><p style="text-align: left;">TALA, PO Box 144722, Austin, TX 78714</p>

<p style="text-align: left;">Phone 1: 512.459.8252<br> Phone 2: 800.526.8252<br> Fax: 512.247.2538<br> Email: <a href="mailto:info@talarts.org">info@talarts.org</a></p>

</address><

**Comment by mr-bobz** [comment]
Done

**Comment by christosptr** [comment]
@mr-bobz Hi Bobby all the contact details need to be in the address tag
this include the phone numbers as well.

**Comment by mr-bobz** [comment]
ok, done

**Comment by christosptr** [comment]
Thanks Bobby. Verified
