### ISSUE TITLE
The footer is not displayed on HTC mobile

### ISSUE THREAD

**Issue by christosptr** [mr-bobz/talarts#135]
![image](https://cloud.githubusercontent.com/assets/5661003/11014805/664e1930-859a-11e5-9e2e-a441d54ee7fb.png)

The footer is not displayed on HTC mobile so I am not able to navigate to the site map, the home page and the accessibility page

**Comment by mr-bobz** [comment]
I think we have around 3-4 defects on this same issue :-)  Fixed now, pls retest. Working fine on my Note.

**Comment by christosptr** [comment]
working Thanks @mr-bobz

**Comment by christosptr** [comment]
verified
