### ISSUE TITLE
Contrast Issues with achecker

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#136]
![image](https://cloud.githubusercontent.com/assets/15111528/11015254/09e2647e-85ab-11e5-9d49-9fd75371f4bf.png)

**Comment by HerinHentry** [comment]
![image](https://cloud.githubusercontent.com/assets/15111528/11015665/e64d85f6-85ba-11e5-8f38-c0ce4e41d2fb.png)

**Comment by mr-bobz** [comment]
Fixed

**Comment by HerinHentry** [comment]
Issues with mobile menus (Active Primary menu & selected submenu)

![image](https://cloud.githubusercontent.com/assets/15111528/11020405/13db748e-8673-11e5-8011-1bac959f3d0e.png)

![image](https://cloud.githubusercontent.com/assets/15111528/11020408/2e8a127c-8673-11e5-90c3-abdc7c6fb41a.png)

![screenshot_2015-11-08-15-23-35](https://cloud.githubusercontent.com/assets/15111528/11020396/e1b60bcc-8672-11e5-9666-1087dedc0e79.png)

**Comment by mr-bobz** [comment]
Fixed

**Comment by HerinHentry** [comment]
@mr-bobz Can you please have a look at this? 4 colour contrast issues with achecker.
[achecker_2015-11-10_11-19-37.pdf](https://github.com/mr-bobz/talarts/files/30785/achecker_2015-11-10_11-19-37.pdf)
