### ISSUE TITLE
Join our e-list and Sign Up Now positioning be fixed in mobile

### ISSUE THREAD

**Issue by ruchitamanuja** [mr-bobz/talarts#137]
In mobile the Join our e-list and Sign Up now are not positioned well. 
This needs to be fixed. 

![sign up now and join our list](https://cloud.githubusercontent.com/assets/15117771/11015294/daebfb2e-85ac-11e5-8f08-5ded4f023695.png)

**Comment by mr-bobz** [comment]
Fixed

**Comment by ruchitamanuja** [comment]
Issue fixed can be closed
