### ISSUE TITLE
Publications page uses table for layout.

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#138]
http://talarts.knowbility.org/services/publications/

Please change the table to a layout page builder. No need for table on this page.
This is an accessibility issue.

**Comment by ruchitamanuja** [comment]
Fixed. Let me know if the formatting is okay.

**Comment by christosptr** [comment]
FYI if we use a table for layout then you can use the role=presentation and screen readers will ignore the table

**Comment by HerinHentry** [comment]
Thank you @christosptr . 
The page has been changed to be consistent with other pages. Hence closing this issue.
