### ISSUE TITLE
JAWS when the focus is on the first menu item "Event" arrows do not work

### ISSUE THREAD

**Issue by christosptr** [mr-bobz/talarts#139]
Using JAWS and setting the focus on the event menu items with JAWS I am not able to navigate the menu. If I press tab and set my focus on the menu item that has sub-menus then the arrows work

**Comment by christosptr** [comment]
@mustanali @mr-bobz has the dev work for the menu now been completed?

**Comment by mustanali** [comment]
@christosptr I assume that the fix we did [added aria tags to enable the virtual mode].Should be fine now.Assigning back to you

**Comment by christosptr** [comment]
@mustanali @mr-bobz @HerinHentry 

Menu still have issues with JAWS and NVDA navigation 

The correct solution is that once the focus is set on the menu the keyboard navigation is correct and we do not need to change the mode for the keyboard navigation to work

Steve explain that when in Virtual Cursor Mode OFF JAWS seed the dom this is why it works. He also said that the menus are shown and we should hide them from the dom and only show them when they actually show the we activate the sub-menu with the down arrow. 

We finish with Steve at about 3am and he said that he was going to have a look into it a bit more and give us some more feedback on it
