### ISSUE TITLE
Youtube Video Issues

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#14]
Hi Chris, 

Please see my suggestions on the video captioning.
0: 52 : Finished Editing could come in the next frame as it's the continuation after a small pause.
1:13 : they gave us a huge list of deliverables that we had to fill out **in** addition to the
1:28 : **Some of the terminology** can be in one line rather than in 2 screens
1:34 : my brain just **felt** it was gonna explode
1:48 : I contacted **TALA**
1:51 : We are **Texas** 
2:05 : **fulfil** spelling issue 
Also "fulfil service requests" could have come together in one screen
2:25 : things we **didn't** understand
2:35 : annually **a** thousands
2:50 : The sentence could be separated with commas **complicated deals, help them understand...**
3:07 : which is **finish** the movie
3:31 : The sentence could be separated with commas **people who care, people who want to help and ...**
3:57 : The sentence could be separated with commas **they care about art, they care about ...**
4:15 : in **a** town
4:20 : artwork, it's the painting, **it's** the music at the bar, **it's** the writing
4:31 : **Isn't** it

Thanks,
Herin

**Comment by christosptr** [comment]
Thanks Herin

just finish from a meeting.I will have a look now

Cheers Christos
Send from my mobile device

**Comment by christosptr** [comment]
Done

**Comment by HerinHentry** [comment]
@ruchitamanuja Can you please retest this issue and see if we have missed any thing? I am thinking few more places might need few punctuations like comma or semi-colon. Can you please have a detailed look and advise? The Video is on the Home page now and we need to turn Closed Caption on to test this. Please assign back to @christosptr with the issues that need to be looked after. The ones in bold are the corrections done now. Few are still missing.
Thanks,
Herin

**Comment by ruchitamanuja** [comment]
[Video Captioning - Down Under.docx](https://github.com/mr-bobz/talarts/files/24833/Video.Captioning.-.Down.Under.docx)
Attached document file for missing words

**Comment by christosptr** [comment]
I am working form the document that ruchita out on Slack

**Comment by christosptr** [comment]
caption is now done
