### ISSUE TITLE
Menu width issues in mobile 

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#140]
Primary menu and sub menu background does not align well. This is not an accessibility concern. But, good to fix if we have time. The indent is set on submenu items. It will be better if the menu backgrounds are of the same size.

**Comment by HerinHentry** [comment]
I will attach screenshot later when i gwt to the laptop

**Comment by HerinHentry** [comment]
![screenshot_2015-11-08-11-34-12](https://cloud.githubusercontent.com/assets/15111528/11019917/74fc7aee-8662-11e5-8378-4c0457a08b6b.png)

**Comment by mr-bobz** [comment]
I think it is by design to easily distinguish main menu items.

**Comment by HerinHentry** [comment]
Ok. Can close this off.
