### ISSUE TITLE
Headings in all caps need to be changed as this is a potential accessibility concern.

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#143]
@christosptr : Can you please advise on this?

![image](https://cloud.githubusercontent.com/assets/15111528/11020070/dc1610f0-8667-11e5-9a5a-e756bad5c978.png)

identified in page : http://talarts.knowbility.org/services/whatwedo/
All other pages need to be checked.

**Comment by christosptr** [comment]
This is a titile/section so for me it looks ok however it does look like screaming so it may look better if we change it to low case

**Comment by HerinHentry** [comment]
Thank you @christosptr .Assigning to @anoopm7 to work on this issue.

**Comment by mr-bobz** [comment]
Done, it was being changed via CSS in our theme. Actual heading is proper case!

**Comment by HerinHentry** [comment]
Thanks @mr-bobz . Issue can be closed.
