### ISSUE TITLE
Contact page _ Email ids not wrapping inside the cell in small screen device

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#144]
![screenshot_2015-11-08-11-53-15](https://cloud.githubusercontent.com/assets/15111528/11020170/2e176888-866b-11e5-9ddf-ee24febd1eca.png)

**Comment by mr-bobz** [comment]
By default wrapping occurs only with white space, changed CSS to break word

**Comment by HerinHentry** [comment]
![image](https://cloud.githubusercontent.com/assets/15111528/11033643/016fd31e-8739-11e5-9f18-065be513e308.png)
Can be closed.
