### ISSUE TITLE
Menu issue _ Right arrow navigation to be fixed

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#145]
Minor issue is the right arrow gets back to the parent menu when a submenu is open. 

Expected behaviour is Esc / left arrow moves the focus back to the current parent menu, Right arrow moves the focus to next parent menu.

**Comment by mustanali** [comment]
Fixed with the assumption that there is no nested submenu within submenu.I had to disable my generic code that was handling opening of submenu within submenu using right arrow.But that doesnt matter but just FYI.Assigning to you @HerinHentry please verify and close.

**Comment by HerinHentry** [comment]
Issue fixed. Retest successful. Closing the issue
