### ISSUE TITLE
Suggestion for menu improvments

### ISSUE THREAD

**Issue by christosptr** [mr-bobz/talarts#146]
Can we please add the following 

Current HTML code
<nav itemtype="http://schema.org/SiteNavigationElement" itemscope="" aria-label="Primary Menu" role="navigation" class="main-navigation" id="site-navigation">

Suggested Code
<nav itemtype="http://schema.org/SiteNavigationElement" itemscope="" aria-label="Primary Menu. To navigate the menu with JAWS, turn JAWS Virtual Cursor Mode Off and use the arrow keys. For more information visit the accessibility page link in the footer" role="navigation" class="main-navigation" id="site-navigation">

**Comment by mustanali** [comment]
Done!
