### ISSUE TITLE
Space in FAQ tabs is causing issues in mobile view _ A whole blank page (see screenshot)

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#149]
@christosptr : Can you please look into this and see if this needs to be fixed?
I think if we could make the boxes to by dynamic sice rather than fixed height, that will be good.

![image](https://cloud.githubusercontent.com/assets/15111528/11025294/7bfece60-86ed-11e5-95a7-6b574ceb54f9.png)

![screenshot_2015-11-09-14-24-56](https://cloud.githubusercontent.com/assets/15111528/11025383/78a02e52-86ee-11e5-9914-136f91caedd1.png)

![screenshot_2015-11-09-14-25-03](https://cloud.githubusercontent.com/assets/15111528/11025384/78a982c2-86ee-11e5-904a-0145b89c901d.png)

**Comment by christosptr** [comment]
Yes I saw that too. I spoke with Mustan. He will have a look tonight

**Comment by HerinHentry** [comment]
@christosptr . Thank you. Assigning to @mustanali .

**Comment by HerinHentry** [comment]
https://dequeuniversity.com/library/aria/tabpanels-accordions/tabbed-accordion
@mustanali : This accordion is good one. Please check.

**Comment by mustanali** [comment]
Looks like FAQ page is changed again to the one without accordian.Not sure if intentionally.am i missing anything.

**Comment by HerinHentry** [comment]
It's back to the original one. Please look into the issue.

**Comment by mustanali** [comment]
@christosptr @HerinHentry this has been fixed.Please check and close.
