### ISSUE TITLE
Table missing summary in Donate Page

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#150]
<...table summary="This table of Contribution Levels gives 
    the Level, Amount, Impact (row headings) of your generous donations">

With that summary, a person who is using a screen reader will have an overview of the table layout before he starts to read it.

**Comment by christosptr** [comment]
Good catch I was also think that we need to move the table after the
donation form. What do you think. If people want more information they can
look at the end

**Comment by HerinHentry** [comment]
@christosptr : I think the users need to know about the Contribution levels before they start deciding on what level they want to choose. Usability is to have it on top / to have a link (internal page anchor) to move to the location.
What do you think?

**Comment by christosptr** [comment]
I understand the usability site of things but it feels that the table takes
to match real estate. Let me have a look again when I am at my computer.

**Comment by christosptr** [comment]
done! @HerinHentry  Can you please test and close

**Comment by HerinHentry** [comment]
Table is accessible. Issue can be closed.
