### ISSUE TITLE
New video on Home page

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#151]
The current video player do not have captions supported.
@christosptr  : Are we able to provide the track for this and see if we can link them together?
![image](https://cloud.githubusercontent.com/assets/15111528/11050484/817b31be-879a-11e5-8d58-8ada47fdb4b4.png)
[Video_Code.txt](https://github.com/mr-bobz/talarts/files/30485/Video_Code.txt)

**Comment by christosptr** [comment]
@HerinHentry has anyone change the link to the caption video? Is not an issue to fix this but it concerns me since we need to keep redoing work already completed. How can we be sure that no other parts of the website will not change and we simply miss report an issues and fix

**Comment by christosptr** [comment]
aa yes I just saw there was work done to fix the issue that keyboard was getting trapped
All good 
@mr-bobz and @HerinHentry 
This is the link to the caption video
https://www.youtube.com/watch?v=FprQKc0bCKY

I tried to add it to the home page but is not working Bobby where do I need to make the change to point the video player to the correct url

**Comment by christosptr** [comment]
Here are the trow file extensions for the captions. I change them to txt cause the .vtt and .sbv extensions are not supported

[captions.vtt.txt](https://github.com/mr-bobz/talarts/files/30566/captions.vtt.txt)
[captions.sbv.txt](https://github.com/mr-bobz/talarts/files/30565/captions.sbv.txt)

**Comment by christosptr** [comment]
done

**Comment by HerinHentry** [comment]
Excellent. Closing the issue
