### ISSUE TITLE
Accessibility page _ Tables do not have caption, scope, summary

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#154]

**Comment by christosptr** [comment]
I have added the Summary tag @HerinHentry do you want to also add scope or caption?

I think is okay but just wanted to double check with your before closing

**Comment by HerinHentry** [comment]
Yes Chris. Scope & Captions are necessary.
Scope tells the screen reader when they use ALT+F5, the cell corresponds to which row and column. Caption will be the title of the table displayed on the page.

Can you please make changes to this?

**Comment by christosptr** [comment]
I have added caption as well and tested the tables using Ctrl+Alt+ arrow keys with JAWS and NVDA and it works as expected. 

scope is already there

**Comment by christosptr** [comment]
can you please have a look I am not sure what else need to be done

**Comment by christosptr** [comment]
got it

**Comment by christosptr** [comment]
done :) Yes much better now

**Comment by christosptr** [comment]
Tested it with NVDA and JAWS

**Comment by HerinHentry** [comment]
We do not need scope on both row headers and columns for this simple table. Only row scope is enough.
As this is a 6 rows with 2 columns table, users are going to be fine. I think we can remove the column level scope. Issue here is the styling on the table only says row headers. So, we should be consistant.
![image](https://cloud.githubusercontent.com/assets/15111528/11090421/d71f3b52-88c5-11e5-8d57-da5f31225fde.png)
