### ISSUE TITLE
When there is no search results, pls display no results found on the page

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#157]

**Comment by HerinHentry** [comment]
fixed

**Comment by HerinHentry** [comment]
To remove the search components inside the search results page.

**Comment by mr-bobz** [comment]
Done

**Comment by mr-bobz** [comment]
For future reference, the original issue was caused as a side effect of this fix - https://github.com/mr-bobz/talarts/issues/97

**Comment by HerinHentry** [comment]
Issue is fixed. Page satisfies the structure. A little Best practice would improve the accessibility.
**Please add tab index to the result below**
![image](https://cloud.githubusercontent.com/assets/15111528/11089002/8270b91a-88ba-11e5-9879-42b08eb11fdf.png)

**Comment by mr-bobz** [comment]
done

**Comment by HerinHentry** [comment]
Excellent! Closing issue.
