### ISSUE TITLE
Monochrome _ Accessibility Tool bar not working in IE

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#158]

**Comment by mr-bobz** [comment]
It is not our code, plugin implementation. 

If required we can list this in known issues in our Accessibility page.

**Comment by mr-bobz** [comment]
Also usually we need to be accessible only on one browser. For eg: IBM products claims accessibility only for Firefox as it is the most standards compliant browser.

**Comment by HerinHentry** [comment]
@christosptr can we please include this in our accessibility page?

Sent from my phone

<div>-------- Original message --------</div><div>From: Bobby Joseph notifications@github.com </div><div>Date:10/11/2015  5:04 PM  (GMT+10:00) </div><div>To: mr-bobz/talarts talarts@noreply.github.com </div><div>Cc: HerinHentry herinnisha@gmail.com </div><div>Subject: Re: [talarts] Monochrome _ Accessibility Tool bar not working in IE
  (#158) </div><div>
</div>Also usually we need to be accessible only on one browser. For eg: IBM products claims accessibility only for Firefox as it is the most standards compliant browser.

**Comment by HerinHentry** [comment]
Thanks @bobbyjoseph

Sent from my phone

<div>-------- Original message --------</div><div>From: Bobby Joseph notifications@github.com </div><div>Date:10/11/2015  5:02 PM  (GMT+10:00) </div><div>To: mr-bobz/talarts talarts@noreply.github.com </div><div>Cc: HerinHentry herinnisha@gmail.com </div><div>Subject: Re: [talarts] Monochrome _ Accessibility Tool bar not working in IE
  (#158) </div><div>
</div>It is not our code, plugin implementation.

If required we can list this in known issues in our Accessibility page.

**Comment by HerinHentry** [comment]
@christosptr : I am assigning this to you to include a accessibility statement on the page about Firefox as recommended browser. Please close this issue once done.
