### ISSUE TITLE
Breadcrub error with the aria-label

### ISSUE THREAD

**Issue by christosptr** [mr-bobz/talarts#160]
HTML with Error
<h1 aria-label="breadcrumb navigation"><div id="breadcrumbs" role="region"><span xmlns:v="http://rdf.data-vocabulary.org/#">\<strong class="breadcrumb_last">Home</strong></span></div></h1>
The aria-label need to move from h1 to the div

<h1 ><div id="breadcrumbs" role="region" aria-label="breadcrumb navigation"><span xmlns:v="http://rdf.data-vocabulary.org/#">\<strong class="breadcrumb_last">Home</strong></span></div></h1>

**Comment by mr-bobz** [comment]
Done

**Comment by christosptr** [comment]
verified
