### ISSUE TITLE
Sign Up now Form

### ISSUE THREAD

**Issue by christosptr** [mr-bobz/talarts#161]
Comments from Steve 

"The signup form looks fine, fields and the drop-down are labeled.  Only thing I have to ask is does the form do any sort of in-line validation on the Email address?  Regardless, we may want to set type="email" rather than type="text" so that iOS will show the Email keyboard with the at symbol. "

**Comment by mr-bobz** [comment]
Sign Up form is an external website, we cannot change anything there

**Comment by christosptr** [comment]
ok will close then
