### ISSUE TITLE
Transcript Link for the Video Editor

### ISSUE THREAD

**Issue by christosptr** [mr-bobz/talarts#162]
Is it possible to add an aria-label to the Transacript link

Current HTML Code
<a class="video-transcript-link" href="/avl-video/tala-promo-video/?transcript=true">Transcript<span class="screen-reader-text"> to Nicole Elmer and Blair Dancy talks about TALA services in this video</span></a>

Change to HTML code
<a class="video-transcript-link" href="/avl-video/tala-promo-video/?transcript=true" aria-label="Transcript for the video of Nicole Elmer and Blair Dancy talking about TALA services">Transcript<span class="screen-reader-text"> to Nicole Elmer and Blair Dancy talks about TALA services in this video</span></a>

**Comment by mr-bobz** [comment]
Wouldn't <span class="screen-reader-text"> to Nicole Elmer and Blair Dancy talks about TALA services in this video</span> suffice? I can try adding, but wondering it would be a repetition for screen readers

**Comment by mr-bobz** [comment]
Done, pls verify, thanks

**Comment by christosptr** [comment]
when you put the aria-label it will over write the title. I was more
thinking to make it more natural English speaking. This is not a high
severity. Let focus on the menu and if we have time we can do this one
other wise no problem

Cheers Christos
Send from my mobile device

**Comment by christosptr** [comment]
@HerinHentry what do you think should we close this defect

**Comment by HerinHentry** [comment]
Aria Labels are not necessary for text links. Moreover, the user has access to the context from other areas of the website like headers, videos etc. I think this is not a high priority as we have other issues. 
We can close this off.

**Comment by mr-bobz** [comment]
Github removes html elements when pasted in comments. I meant to ask about the span tag inside that link meant for screen readers. Anyway added the aria-label as you wanted already.
