### ISSUE TITLE
Distractive spinner on the Video when the page loads (Not while playing)

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#163]
There is a small spinner in the poster image when trying to load data.

<...video class="wp-video-shortcode" id="video-8-3" width="640" height="360" poster="/wp-content/uploads/2015/11/TALA_Video_Poster.jpg" **preload="metadata"** controls="controls">

Suggestion : Can we please try using preload="auto"?

![image](https://cloud.githubusercontent.com/assets/15111528/11088875/ac1d648a-88b9-11e5-9e19-93ab19f7a0b8.png)

**Comment by mr-bobz** [comment]
preload="auto" would not show the loading spinner?

**Comment by mr-bobz** [comment]
The video is added using a short code/plugin. I added there, don't think it is supported by plugin though.
[avl_video id="1031" preload="auto"]

**Comment by HerinHentry** [comment]
It works. Closining.
