### ISSUE TITLE
Donate Page _ Error Message Contrasts issue

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#24]
![image](https://cloud.githubusercontent.com/assets/15111528/10797034/dfbd075c-7df4-11e5-852e-4b585a5d6de2.png)

**Comment by HerinHentry** [comment]
The contrast issue is fixed. But, the Colour and Aesthetics don't look good.Can we please clear the yellow background and make it white background and red text? 
Using colour alone for information is not a problem as the text specifically says about the error.

**Suggestion : **
This is a required field can be changed to **This field is required**

![image](https://cloud.githubusercontent.com/assets/15111528/10955333/38040ade-83a7-11e5-8614-c74bc2266748.png)

yet to test : Focus change to the error field.

**Comment by anmolpatel** [comment]
@HerinHentry please re-test

**Comment by HerinHentry** [comment]
![image](https://cloud.githubusercontent.com/assets/15111528/11020330/3549e892-8670-11e5-8683-2e80500e4ac7.png)

Contrast passes Level AA. Can close this issue.
