### ISSUE TITLE
Event Page _ Comments disable on Posts

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#27]

**Comment by mr-bobz** [comment]
I have set default as disabled for future posts (Settings -> Discussion). For existing posts, go to All posts and use the 'Quick Edit' option under each post in the list mode to disable comments as shown below.
![6606f3c2cd1b9c35](https://cloud.githubusercontent.com/assets/12365601/10864549/7e48b658-8045-11e5-859c-5b46f2e3d44f.jpg)

**Comment by mr-bobz** [comment]
All posts updated
