### ISSUE TITLE
When Navigating from one submenu to another website breaks

### ISSUE THREAD

**Issue by christosptr** [mr-bobz/talarts#30]
Reproduction Steps
1 click on the sub-menu  Join Us » Members
2 quickly go to the menu and click on the Join Us » Volunteers

Expected Result
The Volunteers page is loaded

Actual Result
An error message is displayed.  
"THIS IS SOMEWHAT EMBARRASSING, ISN'T IT?"
This issue appears to be an intermittent issue and it may have to do with the server load

Browser: Chrome
OS: Windows7

**Comment by christosptr** [comment]
![sitebreakwhennivigatingtoofast](https://cloud.githubusercontent.com/assets/5661003/10846735/f2460654-7f65-11e5-9055-950fd45d616f.JPG)

**Comment by HerinHentry** [comment]
@christosptr Is this still happening? Can you please check?

**Comment by christosptr** [comment]
I cannot reproduce anymore. It could be that it was during time that people were making updates on the website
