### ISSUE TITLE
The home link on the Site Map has inconsistent name

### ISSUE THREAD

**Issue by christosptr** [mr-bobz/talarts#31]
1 Click on the Home link on the Menu 
2 Page load and you see the home in the breadcrumb
3 Now go to the site map

Expected result
The home link should be listed in the site map

Actual Result
The home link is not shown in the site map
Instead the title "Texas Accountants and Lawyers for the Arts (TALA)" is shown

This is not consistent and it can cause issues to people with cognitive disability

**Comment by christosptr** [comment]
![sitemap](https://cloud.githubusercontent.com/assets/5661003/10847229/13d6c5b2-7f69-11e5-909a-f1f3fef6931c.JPG)

**Comment by mr-bobz** [comment]
For the home page the sitemap plugin is automatically showing the site title. I changed the Home page title, but it doesn't make any diff. I think we have to mark it as a known issue for now!

**Comment by mr-bobz** [comment]
Btw, I removed 'Home' from menu and added a title to logo (clicking on it takes to home page). Users can also use the breadcrumb to go back to Home.
