### ISSUE TITLE
Change Menu Structure as per TALA's request

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#32]
Events-Primary tab

Services-Primary tab
    What we do?  (Called Services)  Secondary
    Do I Qualify? Secondary
    Membership Secondary
    Request Assistance Secondary
    Publications secondary

Support-Primary tab
    Donate-Secondary
    Volunteer-(Combine becoming a volunteer here) Secondary

About-primary tab
    Mission-Secondary
    Board and Staff-Secondary
    Contact-Secondary
    FAQ's-secondary

**Comment by HerinHentry** [comment]
@christosptr :The Menu and the page structure has been changed as per TALA's request. Can you please check the breadcrumbs when you are testing?
Thank you,
Herin

**Comment by christosptr** [comment]
sure will check it again

**Comment by HerinHentry** [comment]
@christosptr The Primary menus are now non-clickable menus. Only the sub-menus are clickable.
There are some placeholder pages to fill the breadcrumbs. We can include a short code inside these pages to include the child pages.
@mr-bobz Do you have any short codes for the About page, Services page and Support page to display their child pages? These pages are not accessible from Menu. They are accessible only from sitemap.

**Comment by mr-bobz** [comment]
Why do you want to display child pages? In case someone opens it via sitemap?

**Comment by mr-bobz** [comment]
I updated page title and menu to match TALA menu names

**Comment by HerinHentry** [comment]
Yes. Just for the site map

**Comment by mr-bobz** [comment]
Done, added child page list via this plugin's short code:
https://wordpress.org/plugins/list-pages-shortcode/
