### ISSUE TITLE
Video does not show captions on mini iPad

### ISSUE THREAD

**Issue by christosptr** [mr-bobz/talarts#33]
Reproduction Steps
Using mini iPad
1 Go to the home page
2 Start the Video

Expected Result
Be able to activate captions

Actual Result
I do not see the option CC on the video player to activate captions when using the min iPad

**Comment by HerinHentry** [comment]
Tested on iPad Air. Video captions available.

**Comment by christosptr** [comment]
works when you maximize the video player

**Comment by christosptr** [comment]
verified with mini iPad. This is an issue with iPads once you zoom into the video you are able to see the caption button on the video player. Closing issue
