### ISSUE TITLE
AVT3 JAWS is getting trapped on the video player

### ISSUE THREAD

**Issue by christosptr** [mr-bobz/talarts#34]
Reproduction steps 
1 Start JAWS
2 Start Firefox
3 Navigate to the home page
4 tab until you set the focus on the video player.
5 Try to navigate after the video

Expected Result 
You should be able to navigate after the video player

Actual Result
Not able to navigate after the video player. The focus is trapped in the video player. This happens when you also do simple keyboard navigation with out JAWS.
Pressing Shift+Tab will eventually get out of the video player

**Comment by HerinHentry** [comment]
This is a critical issue if we have keyboard trap.Can we please look into this as high priority?

**Comment by mr-bobz** [comment]
Changed video implementation, pls retest

**Comment by christosptr** [comment]
done
