### ISSUE TITLE
Search Test box is not style correctly

### ISSUE THREAD

**Issue by christosptr** [mr-bobz/talarts#35]
Reproduction Steps
1 Using keyboard navigate to the Search text box

Actual Result
The search text box is shown but the style is not correct (see attachment)

Expected Result
The search text box is shown with the correct style

**Comment by christosptr** [comment]
![searchtextbox](https://cloud.githubusercontent.com/assets/5661003/10851093/5d120570-7f7d-11e5-84b0-ea8598f03290.JPG)

**Comment by HerinHentry** [comment]
![image](https://cloud.githubusercontent.com/assets/15111528/10861744/deef674c-7fdf-11e5-8952-226602b32c8c.png)
This is the screenshot from firefox.Can you please advise which browser you are testing?

**Comment by mr-bobz** [comment]
I believe this happens only when the browser width is not enough to show the search box along with the menu items. So it wraps.
