### ISSUE TITLE
The menu drop down does not have the correct style

### ISSUE THREAD

**Issue by christosptr** [mr-bobz/talarts#36]
Repro Steps
1 Keyboard navigate to one of the sub menu items of the About Us menu

Actual result
the styling is not looking nice. See attachment

Expected Result
A smoother edge of the sub menu item

**Comment by christosptr** [comment]
![menustylingnotcorrect](https://cloud.githubusercontent.com/assets/5661003/10851183/ba8a25d4-7f7d-11e5-9e4a-5a7243d00694.JPG)

**Comment by mr-bobz** [comment]
Fixed with new menu color changes
