### ISSUE TITLE
Spelling Errors in webpage _ Every spelling error 1 mark reduced.

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#37]
Link : http://talarts.knowbility.org/support/volunteer/

What is the time commitment?

The time commitment varies for each case, but generally, TALA cases are fairly brief in nature. TALA does not provide ongoing representation with the same attorney or **accoutant**, so once you complete the matter, you are released. Although preparation of Form 990 is not time intensive, it can lend itself to an annual assignment.

**Comment by ruchitamanuja** [comment]
![image](https://cloud.githubusercontent.com/assets/15117771/10862362/efb3c050-7ff8-11e5-93d6-b0e88a78e006.png)
Fixed
