### ISSUE TITLE
Spelling Error _ Menu Bar

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#38]
**Menubar** instead of **Menu Bar**
http://talarts.knowbility.org/accessibility/

**Comment by ruchitamanuja** [comment]
![image](https://cloud.githubusercontent.com/assets/15117771/10862378/65e73d2e-7ff9-11e5-87bd-cb599ffb4d2e.png)
![image](https://cloud.githubusercontent.com/assets/15117771/10862379/6c0d2ac4-7ff9-11e5-8a37-42e443217706.png)
