### ISSUE TITLE
IE _ The CSS entry point backgrounds not loading properly.

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#41]
Default
![image](https://cloud.githubusercontent.com/assets/15111528/10874255/6079a124-8175-11e5-9a6f-b9c73125b1b1.png)

The Hover colour is white and hence not visible when the page has load issues.

**Comment by mr-bobz** [comment]
Fixed missing gradient for IE

**Comment by HerinHentry** [comment]
Tested. Can be closed.
