### ISSUE TITLE
Empty Header in Volunteer page <h2></h2>

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#43]
http://talarts.knowbility.org/support/volunteer/
Inspect Code and h2 element found empty

**Comment by ruchitamanuja** [comment]
![image](https://cloud.githubusercontent.com/assets/15117771/10903999/b3e31fea-8263-11e5-804f-2807551f9ae1.png)
Fixed

**Comment by HerinHentry** [comment]
Thank you. Issue Fixed. Defect can be closed.
