### ISSUE TITLE
Become Member and Become Volunteer to be renamed as "Become a Member" & "Become a Volunteer"

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#46]

**Comment by christosptr** [comment]
@HerinHentry I am ok with the "Become Member" and "Become Volunteer". What do you think
@mr-bobz Bobby do you plan to fix this issue?

**Comment by HerinHentry** [comment]
@manuum Will it be possible to get one image with Become a Member and one with Become Member? 
@christosptr I did a google check and it's standard practice to use Become a member.
![image](https://cloud.githubusercontent.com/assets/15111528/10990400/cc0debdc-84a6-11e5-9477-095e076f7e5c.png)
