### ISSUE TITLE
Contact Us Section in Footer _ Phone number, Email id to be added.

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#47]
The current contact information in footer has 
TALA, PO Box 144722, Austin, TX 78714

The contact Us page has Phone numbers, Fax, email id as well. Is it possible to include these informations in the footer?
512.459.8252
800.526.8252
Fax: 512.247.2538
info@talarts.org

**Judgement Criteria:**
25.  Contact Information.  Email and/or contact information is provided and easy to find using the address element. Contact information that is not available or hard to find results in a score of 0.

As we have plenty of room in footer, having these details is additional advantage.

**Comment by christosptr** [comment]
Good point. I agree with Herin

**Comment by HerinHentry** [comment]
Prefect. Defect can be closed.
