### ISSUE TITLE
Home Page _ Background needed for Disclaimer text.

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#48]
This Disclaimer message is a very important message. It is good to have a background colour (preferably yellow) to this. This will add some colour to the site.
![image](https://cloud.githubusercontent.com/assets/15111528/10880083/74c6a352-81ac-11e5-9332-536bc1f1fa5b.png)

Sample image: 
![image](https://cloud.githubusercontent.com/assets/15111528/10880096/849a50e4-81ac-11e5-93f0-7c8a9c978441.png)

Reference site: http://www.artslaw.com.au/

**Comment by ruchitamanuja** [comment]
![image](https://cloud.githubusercontent.com/assets/15117771/10908131/87266cb2-8283-11e5-9a71-f48fca7c9db5.png)
Let me know if this is ok. I also created a rounded border around it to match the other items on the page

**Comment by HerinHentry** [comment]
Excellent. Can close the issue.
