### ISSUE TITLE
Move Social Media Icon to the Footer

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#49]
![image](https://cloud.githubusercontent.com/assets/15111528/10880246/cafecd52-81ad-11e5-8121-3101aa050ff3.png)

Can we please move the Social Media Icon to the footer? This is the common practice  + I think this will look a bit more tidier.

**Comment by mr-bobz** [comment]
Done

**Comment by HerinHentry** [comment]
Excellent! Issue is fixed.
