### ISSUE TITLE
Create a Last updated date on the footer

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#5]
As per the Wordpress judging form we need to include Last Updated Date on the footer of the page.Can you please check if any Widgets / code can be changed to accomodate this?

**Comment by HerinHentry** [comment]
@christosptr & @mr-bobz Is this Last updated field for the whole website or page specific?

**Comment by mr-bobz** [comment]
@HerinHentry, it is for the whole site
https://wordpress.org/plugins/site-last-modified/
