### ISSUE TITLE
HTC mobile does not show the TALA logo

### ISSUE THREAD

**Issue by christosptr** [mr-bobz/talarts#51]
When browsing the talarts.knowbility.org website with an adroid htc mobile the log is not shown

**Comment by christosptr** [comment]
![screenshot_2015-11-02-23-12-47](https://cloud.githubusercontent.com/assets/5661003/10882420/a3be0972-81be-11e5-87ee-b0e4acf9bea2.png)

**Comment by HerinHentry** [comment]
This is happening on Android mobiles.

**Comment by christosptr** [comment]
Guys what do we want to do with this one @mr-bobz @anmolpatel @HerinHentry

**Comment by mr-bobz** [comment]
Should be fixed now. 

Duplicate of #58?

**Comment by christosptr** [comment]
Verified
