### ISSUE TITLE
Broken link in Do I Qualify Page

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#52]
http://talarts.knowbility.org/services/do-i-qualify/

![image](https://cloud.githubusercontent.com/assets/15111528/10883013/485ca656-81c3-11e5-9792-ea4d1ea5cdc9.png)

**Comment by ruchitamanuja** [comment]
Updated the link to http://talarts.knowbility.org/services/membership/

**Comment by HerinHentry** [comment]
Issue can be closed.
