### ISSUE TITLE
Sponsor Logos need a background border to make it more clear.

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#53]
![image](https://cloud.githubusercontent.com/assets/15111528/10883058/840660ca-81c3-11e5-94a1-7a8c8d210d2d.png)

The Houston Endownment logo in the desktop is very small and it kind of blends with the background. We need a little border / some kind of contrast to distinguish

**Comment by ruchitamanuja** [comment]
I have added a background colour of #FFFFFF around the widget. 
![image](https://cloud.githubusercontent.com/assets/15117771/10908691/99065d12-8287-11e5-815a-1006c29cf437.png)

**Comment by HerinHentry** [comment]
Can close this issue as the background is there. But, as the widget link does not work, will have to introduce another widget.
