### ISSUE TITLE
Board and Staff _ Formatting issue

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#55]
http://talarts.knowbility.org/about/boardandstaff/

The page displays visual text editor content.

**Comment by ruchitamanuja** [comment]
![image](https://cloud.githubusercontent.com/assets/15117771/10904722/7075452a-8269-11e5-93d9-d27f294c3d0e.png)
Already fixed

**Comment by HerinHentry** [comment]
Issue Fixed. Can be closed.
