### ISSUE TITLE
The Posts displayed on Search results do not have a continue reading link

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#57]
![image](https://cloud.githubusercontent.com/assets/15111528/10883437/190b0818-81c6-11e5-905d-73acede755a7.png)

Only pages show the link

**Comment by mr-bobz** [comment]
I see it working when the content is truncated. It is showing all contents in the list when more link is missing

**Comment by HerinHentry** [comment]
Thanks @mr-bobz . That makes sense. As the link is lost, are we able to truncate the search results to certain characters so that every result links to a detailed page?
![image](https://cloud.githubusercontent.com/assets/15111528/10906950/f036c4f4-8279-11e5-92f9-8660b0d68fb4.png)

**Comment by mr-bobz** [comment]
Why do you want to show detailed page link when there is no more information on the page/post?

**Comment by HerinHentry** [comment]
The users expectation is to take to the actual page. As we have to keep the user experience consistent (especially for accessibility) this link is necessary.

**Comment by HerinHentry** [comment]
This is the normal user experience. Title + content excerpt. 
![image](https://cloud.githubusercontent.com/assets/15111528/11002191/6b41e804-84ff-11e5-990a-5a3dbd39ce75.png)

![image](https://cloud.githubusercontent.com/assets/15111528/11002223/a03943c2-84ff-11e5-8d36-a5fdcd901581.png)
