### ISSUE TITLE
Mobile Menu being displayed as blue

### ISSUE THREAD

**Issue by ruchitamanuja** [mr-bobz/talarts#58]
The mobile menu is being displayed as blue still. 

Steps to Reproduce:
1.Go to homepage on a mobile 
2. Notice the mobile menu 

Expected Result:
Menu should be as per minimized desktop menu 

Actual Result:
Old Blue menu is being displayed 
![screenshot_2015-11-02-18-43-20](https://cloud.githubusercontent.com/assets/15117771/10903136/a25ea784-825a-11e5-827c-56c3c17b67bd.png)

**Comment by mr-bobz** [comment]
I believe this issue is fixed. Had to Disable 'Mobile Theme' in Jetpack plugin
