### ISSUE TITLE
Sponsor Logos in Home page do not have href link set.

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#60]
![image](https://cloud.githubusercontent.com/assets/15111528/10904975/3ec91612-826b-11e5-939a-785ce452da91.png)

**Comment by ruchitamanuja** [comment]
![image](https://cloud.githubusercontent.com/assets/15117771/10908602/fedeee84-8286-11e5-8393-ed1c02ec072e.png)
The links are added in the widget. When I manually add them in the Text Editor they get lost after saving. @mr-bobz  are you able to please have a look at this?? I think maybe something needs to be done in the widget code. 
https://siteorigin.com/thread/image-grid-widget-how-to-link-individual-images-in-grid/ 
https://siteorigin.com/thread/image-grid/

**Comment by mr-bobz** [comment]
Seems to be a known issue with the Site Origin Image Grid widget, should be fixed in next update:
https://siteorigin.com/thread/image-grid/

Else we have to use just a grid and add images one by one.

**Comment by HerinHentry** [comment]
Yes. This is a site origin image grid's existing problem. Can you please
add a normal text editor and add the images?

**Comment by HerinHentry** [comment]
@ruchitamanuja : Please add a visual editor and make our own grid to resolve the issue.

**Comment by HerinHentry** [comment]
Also, please make rounded corners with css

**Comment by ruchitamanuja** [comment]
@HerinHentry 
Can you please have a look at the home page. As there are 7 logos i have put 4 in top row and 3 in bottom row. However the sizes of the logos are different for bottom row. 
Should the logo's still be on white background?? Or should we change this to transparent? I dont think the white background logos are looking nice.

**Comment by HerinHentry** [comment]
@ruchitamanuja : As the Logos are going to be placed on a background, the while colour should be okay. Can you please check if the background can be changed and the logos can be resized to smaller size to fit in the screen in one line?

**Comment by HerinHentry** [comment]
The logos have href. Can be closed.
