### ISSUE TITLE
Focus Visible Issue _ The focus indicator need to be highlighted a bit more. Is this possible?

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#61]
![image](https://cloud.githubusercontent.com/assets/15111528/10906453/b401f28c-8275-11e5-8481-6e4e1fd93192.png)

**Comment by mr-bobz** [comment]
Changed focus outline to make it more prominent, check and let me know

**Comment by christosptr** [comment]
I also think a blue color is more appropriate. Like what chrome does on the forms 
Green or red are the color most color blind people have issues with

**Comment by HerinHentry** [comment]
@christosptr : Do we have to check the colour contrast for the Focus indicator as well?

**Comment by christosptr** [comment]
I do not think there is a check point for it but its good to have in mind

Cheers Christos
Send from my mobile device

**Comment by HerinHentry** [comment]
I tested this with both monochrome & high colour contrast modes. This looks alright.
I think we should be able to close this issue if you agree with this. @christosptr

**Comment by HerinHentry** [comment]
![image](https://cloud.githubusercontent.com/assets/15111528/10990353/1cf1aa62-84a6-11e5-9296-022c244cbf76.png)
Focus visible. Can be closed.
