### ISSUE TITLE
Board and Staff page shows Title as About

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#62]
![image](https://cloud.githubusercontent.com/assets/15111528/10906482/fa5fe6ee-8275-11e5-9529-ccdefa2dd21c.png)

**Comment by ruchitamanuja** [comment]
@HerinHentry 
Do you want to change the About to 'Board and Staff' ?? Isn't the paragraph about TALA? 
How about I put About TALA ??

**Comment by HerinHentry** [comment]
This page contains About TALA & Board and staff.
The About details are already covered in What we do? page. I reckon this should be called as Board and Staff. But @ruchitamanuja , can you please confirm the content in both pages?

**Comment by ruchitamanuja** [comment]
There is no heading/title anymore:
![image](https://cloud.githubusercontent.com/assets/15117771/10963584/9be06b30-83f5-11e5-818b-7a1f5e5cdb65.png)

**Comment by HerinHentry** [comment]
Board and Staff | Texas Accountants and Lawyers for the Arts (TALA)
What we do? | Texas Accountants and Lawyers for the Arts (TALA)
Issues resolved. Can be closed.
