### ISSUE TITLE
Menu _ Upper case letters need to be changed to Capitalised.

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#63]
![image](https://cloud.githubusercontent.com/assets/15111528/10906525/48e65c1c-8276-11e5-9fb2-8207c8390248.png)

Reference : 
http://webaim.org/techniques/fonts/#caps

![image](https://cloud.githubusercontent.com/assets/15111528/10906663/820fcd74-8277-11e5-8591-9467e344cf58.png)

Note : SERVICES to be changed to Services etc. Every menu item need to be changed.

**Comment by HerinHentry** [comment]
@christosptr Can you please advise on this so that @ruchitamanuja can get started on this fix?

**Comment by HerinHentry** [comment]
@ruchitamanuja Please change all the Upper case menu items to Capitalised menu items. Thank you.

**Comment by ruchitamanuja** [comment]
@HerinHentry 
I have no idea why this is in upper case. 
I see them in lower case in the customize menu section: 
@mr-bobz @mustanali - Could you please advise? 
![image](https://cloud.githubusercontent.com/assets/15117771/10908994/dca415f8-8289-11e5-91b0-4eafbafcf5d0.png)

**Comment by mr-bobz** [comment]
Fixed now, that was being done by the theme style (text-transform: uppercase;)

**Comment by christosptr** [comment]
Verified
