### ISSUE TITLE
DALLA's week _ Image not loaded

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#64]
http://talarts.knowbility.org/643/

![image](https://cloud.githubusercontent.com/assets/15111528/10906877/3a6b7142-8279-11e5-9cd5-d9c8bc7319fd.png)

**Comment by ruchitamanuja** [comment]
@HerinHentry 
![image](https://cloud.githubusercontent.com/assets/15117771/10909224/ac519964-828b-11e5-9367-95043bde17fa.png)
Do we have this logo from the client? If not, can we customize their logo? Maybe we need to check with Alysa.

**Comment by HerinHentry** [comment]
@christosptr Can we please check if these colour themes need to be changed?

**Comment by HerinHentry** [comment]
@ruchitamanuja I can't still see the image loaded. Can you please confirm if this is loaded?

**Comment by HerinHentry** [comment]
Please Copy this Logo from the TALA online site and load for now. This s just a decorative image. So please use " " for alt text.

**Comment by ruchitamanuja** [comment]
I have added this blue logo for now. We would need to check with Alysa for updated logo.

**Comment by HerinHentry** [comment]
Image loads. Can be closed.
