### ISSUE TITLE
Adjust the spacing in the footer

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#65]
![image](https://cloud.githubusercontent.com/assets/15111528/10907850/b3eab534-8281-11e5-9fac-de63f31b333f.png)

Tou much line spacing.

**Comment by ruchitamanuja** [comment]
![image](https://cloud.githubusercontent.com/assets/15117771/10909146/0d2431e4-828b-11e5-905f-bfdbbdea0f2f.png)
Adjusted

**Comment by HerinHentry** [comment]
@anoopm7 Can you please give this a go?

**Comment by HerinHentry** [comment]
@anoopm7 Also, can you please move Copyright © 2011-2015 All rights reserved to the end ? It should be the last item on the page.

**Comment by anoopm7** [comment]
done

**Comment by anoopm7** [comment]
however I also need to move social media icons. how do I move them? Is this controlled from css?

**Comment by HerinHentry** [comment]
Please do not touch the Social media icons.
Looks much better now.
Move the Website Last Modified: Nov 5, 2015 - 12:44 PM to End as well. It should be below the knowbility logo. Can we give it a go?

**Comment by HerinHentry** [comment]
Alignment needs a little change as the logo and the date are in the same line
![image](https://cloud.githubusercontent.com/assets/15111528/10967383/54fc7b78-840e-11e5-8700-3f8c69aca6c5.png)

**Comment by HerinHentry** [comment]
![image](https://cloud.githubusercontent.com/assets/15111528/10990325/d403eab8-84a5-11e5-8138-121a347f82a7.png)

Issue resolved. Can be closed.
