### ISSUE TITLE
Home page _ Reduce spacing between Video & Paragraph.

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#66]
![image](https://cloud.githubusercontent.com/assets/15111528/10907893/eb0cab3a-8281-11e5-9824-137ac0d5e39a.png)

**Comment by ruchitamanuja** [comment]
![image](https://cloud.githubusercontent.com/assets/15117771/10909531/0d411d24-828e-11e5-8e83-8bb8b3788ae9.png)
Does this look better ?

**Comment by HerinHentry** [comment]
Much better. Closing issue.
