### ISSUE TITLE
JAWS set focus on the title of the page and announce it

### ISSUE THREAD

**Issue by christosptr** [mr-bobz/talarts#67]
Reproduction steps
1 Start JAWS and keyboard to the menu

Actual Result
Just before the menu I hear 
 "Texas accountant and lawyers for the arts (TALA)" 

Expected Result
This is the title of the page and it should not have been announce in the middle of the page

**Comment by mr-bobz** [comment]
I have set site-title display to none, can you pls retest?

**Comment by christosptr** [comment]
Test and works fine on firefox. I need to test it next with the mini iPad when I go home

**Comment by christosptr** [comment]
verified on mini iPad as well the focus is not set on the title anymore
Thanks Bobby
