### ISSUE TITLE
The header tag <h> need to be in order

### ISSUE THREAD

**Issue by christosptr** [mr-bobz/talarts#69]
HTML Structure

When using Headers we should not skip a header for Example

Starting with h2
then having a h3

Is not correct

It should be H1 then H2 then H3

pages with this issues are
http://talarts.knowbility.org/services/whatwedo/
http://talarts.knowbility.org/about/boardandstaff/

**Comment by HerinHentry** [comment]
@christosptr 
If we fix Issue 70 by adding <h1> to the Title element of the page, this issue will be resolved. The page structure looks good otherwise.
![what we do _ outline](https://cloud.githubusercontent.com/assets/15111528/10950645/d2ab468a-838c-11e5-9ed0-3b7502b0b5c2.PNG)

**Comment by mr-bobz** [comment]
Done, pls check again now, tx

**Comment by christosptr** [comment]
verified
