### ISSUE TITLE
Remove the <h2 class="screen-reader-text">Primary Menu</h2>

### ISSUE THREAD

**Issue by christosptr** [mr-bobz/talarts#70]
Need to remove the HTML tag
<h2 class="screen-reader-text">Primary Menu</h2>

**Comment by christosptr** [comment]
![capture](https://cloud.githubusercontent.com/assets/5661003/10911294/441740bc-8298-11e5-96bd-c14e808ee426.JPG)

**Comment by christosptr** [comment]
This is one example all H2 should be H1 and all H3 should be H2

**Comment by christosptr** [comment]
@HerinHentry The way to fix this was to add the h1 tag on the breadcrumb. This will fix the issues but there is something to this solution that does not resonate with me 

What are you thought Herin?

**Comment by HerinHentry** [comment]
@christosptr The current structure is not proper structure.
Can we try this for few pages? This is the Home page suggestion.
![site outline](https://cloud.githubusercontent.com/assets/15111528/10950469/e1bb1d7c-838b-11e5-9c07-ae7d945d8ac1.png)

**Comment by mr-bobz** [comment]
please retest now, tx

**Comment by christosptr** [comment]
verified
