### ISSUE TITLE
Menu Issue _ Keyboard only navigation. Sub menu does not close

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#71]
Tab into the menu. From Services use the down arrow once to open the sub menu.
Now use the Tab. The Sub menu should close the focus shifts to Support. 

Issue : Sub menu does not close.

![menu issue](https://cloud.githubusercontent.com/assets/15111528/10935737/30b634fc-833c-11e5-9c4f-cbc190c42991.png)

**Comment by mustanali** [comment]
@HerinHentry @christosptr fixed now.
