### ISSUE TITLE
Menu and keyboard navigation

### ISSUE THREAD

**Issue by christosptr** [mr-bobz/talarts#72]
Reproduction steps
1 Using keyboard navigate to the menu
2 Go on to the Services menu item
3 Click the down arrow to select the first submenu item.
4 Click the down arrow few time.

Expected result
The focus moves to the next menu item, The screen does not move

Actual result
Focus move to the next sub-menu item but the screen also move with it. Once we get to the last sub-menu item and continue pressing the down arrow then the screen continues to move until we go to the end of the page. Some how the up and down arrow scroll the page when they should not 

See the menu on knowbility.org. I think this is a good example of a menu

**Comment by christosptr** [comment]
@mr-bobz and @HerinHentry what do you guys think?

**Comment by HerinHentry** [comment]
@christosptr I agree. This is causing a flickering effect and distraction. Background is not locked.

**Comment by mustanali** [comment]
@christosptr @HerinHentry @mr-bobz I have fixed it.Now when you are on menu and use up and down arrow key the page wont scroll.

**Comment by mustanali** [comment]
@christosptr please verify the scroll.I am closing the issue now.

**Comment by HerinHentry** [comment]
@mustanali The scroll issue is still happening.

**Comment by mustanali** [comment]
Herin confirmed again it works except for FF.

**Comment by HerinHentry** [comment]
@christosptr : I tested on IE and Chrome. This scroll issue does not seem to happen. But, Firefox still has the issue. Can you please confirm this at your end?

**Comment by christosptr** [comment]
Same for me works for IE and Chrome but not with Firefox

**Comment by HerinHentry** [comment]
@christosptr , @mustanali , @mr-bobz 
This is a known issue with Firefox + NVDA combination. After a bit of research I found that Sub-menu opens up and **works like a charm with the Alt+Down arrow**

Finally.... Hurray... the menu is working.
@christosptr  : Can you please test this with JAWS (Tab for primary menus, Alt + Down ARROW to open submenus) and update the accessibility page.

The scroll issue is still there in firefox.

**Comment by christosptr** [comment]
sure Thanks for this Herin

**Comment by christosptr** [comment]
this does not work well with JAWS because it opens the file menu

**Comment by christosptr** [comment]
I will do some more testing with JAWS tomorrow at the office with mustan and will see what can be done. I found that changing JAWS to virtual mode off then menu works so we may have to add it on the accessibility page

**Comment by mustanali** [comment]
@christosptr i think this can be closed.I am assigning back to you

**Comment by christosptr** [comment]
this is a duplicate of #145
