### ISSUE TITLE
Join Our E-list <b> to <em>

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#75]
<...b>Join our e-list</b>
Repair: Replace your b (bold) elements with em or strong.

<..em> — for stress emphasis in HTML5, i.e., something screen reader pronounce differently

**Comment by mr-bobz** [comment]
Done

**Comment by HerinHentry** [comment]
The Join our e-list text looks very big. It would be nice if it is the same size of the button.
![image](https://cloud.githubusercontent.com/assets/15111528/10967432/a3f483a6-840e-11e5-8962-b52cbae5589c.png)

**Comment by mr-bobz** [comment]
What browser is above screenshot from? It looks fine (same size as button font) for me. 
@anmolpatel, can you pls change to a span and style using CSS instead?

**Comment by HerinHentry** [comment]
Looks good now. Not sure what has happened earlier. Closing the issue.
![image](https://cloud.githubusercontent.com/assets/15111528/10990249/40665214-84a5-11e5-9b25-6cea08d21f68.png)
