### ISSUE TITLE
Donate _ Form radio buttons are not contained in Fieldset / Legend

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#78]
**Sample code**
<...fieldset>
<...legend>Donut Type</legend>
<...p>
<...input type="radio" name="flavour" id="choc" value="chocolate" checked="checked" />
<...label for="choc">Chocolate</label><br/>
<...input type="radio" name="flavour" id="cream" value="cream"/>
<...label for="cream">Cream Filled</label><br/>
<...input type="radio" name="flavour" id="honey" value="honey"/>
<..label for="honey">Honey Glazed</label>
<../p>
<.../fieldset>

**Comment by HerinHentry** [comment]
@anmolpatel : Fieldset does not contain a legend element. All fieldsets should contain a legend element that describes a description of the field group.
   <...fieldset>
     <...legend>Personalia:</legend>
     Name: <...input type="text"><br>
     Email: <...input type="text"><br>
     Date of birth: <...input type="text">
   <.../fieldset>

**Comment by anmolpatel** [comment]
added fieldset and legends to all sub sections

**Comment by HerinHentry** [comment]
Radio buttons Field set and Legend should be set only to the radio buttons. Not to the whole section.
Can you please redo this?
Please refer to http://webaim.org/techniques/forms/controls for the location of the tags.
![image](https://cloud.githubusercontent.com/assets/15111528/11020370/fafbf9da-8671-11e5-8f00-b7eb06713999.png)

**Comment by anmolpatel** [comment]
<img width="749" alt="screen shot 2015-11-09 at 8 47 42 pm" src="https://cloud.githubusercontent.com/assets/4068650/11030600/3050bd4e-8723-11e5-8a81-0240641e5543.png">

<img width="717" alt="screen shot 2015-11-09 at 8 49 22 pm" src="https://cloud.githubusercontent.com/assets/4068650/11030638/64f1fefa-8723-11e5-8cbc-c0898f765c5c.png">

i dont understand why it is not done correctly, as per the structure of existing HTML thats the only way i could achieve this, unless i have completely missed something

**Comment by christosptr** [comment]
Hi Anmol here is an example of a field set

<fieldset>
    <legend>Personalia:</legend>
    Name: <input type="text"><br>
    Email: <input type="text"><br>
    Date of birth: <input type="text">
  </fieldset>

**Comment by anmolpatel** [comment]
Added fieldset around radio button for donation amount as required

**Comment by HerinHentry** [comment]
@anmolpatel :The location of field set is still not set properly.
Please attach the file with the correct format. This code should be able to go for the radio buttons. We need the fieldset and legend right infront of the radio button group. They should not be outside another container. Same thing apply for every group you are doing. The issue was it was not able to relate the group of radio buttons with the fieldset as the fiedset was in a different container like <div>
Also please avoid the nested fieldsets and legends as this could cause screen reader to panic.
[Radio Buttons_Donate.txt](https://github.com/mr-bobz/talarts/files/31829/Radio.Buttons_Donate.txt)

**Comment by anmolpatel** [comment]
fixed the radio buttons as per your input,
added fieldset for other areas, 
it is quire difficult to modify further inside Tribute Gift section, as i'll have to remove elements from the html and than put them back in.. let me know if i should modify the tribute gift further or not

**Comment by HerinHentry** [comment]
Excellent work! Well done!
