### ISSUE TITLE
Donate _ Order of the field to be changed.

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#79]
I think the First name (required) and then the text box is meaningful for the screen reader.Otherwise it confuses the screen reader users if the required belongs to next field.

![image](https://cloud.githubusercontent.com/assets/15111528/10955187/2a1c360e-83a6-11e5-9fdf-8f82388591a4.png)

@christosptr :Can you please comment on this issue and assign to @anmolpatel to fix?

**Comment by anmolpatel** [comment]
Aesthetic wise it will not look good, thats why i kept it at the end. [ First Name: (required) ___________ ]
Can I instead append an asterisk: First Name: \* to indicate required field ?

**Comment by HerinHentry** [comment]
I think the screen reader users are used to hearing \* for required field. So this shouldn't be an issue. 
@christosptr : What do you think about this?

**Comment by anmolpatel** [comment]
done! Please re-test

**Comment by christosptr** [comment]
sorry for the late response @anmolpatel 
You are correct to say that \* has been used for quite some time but this does not take in to consideration cognitive disabilities. I would suggest changing \*  with  (required)

**Comment by HerinHentry** [comment]
@anmolpatel : In addition to @christosptr 's comment, please also make the (optional) to go with the same field order. Address 2:  has optional at end.

**Comment by anmolpatel** [comment]
done!

**Comment by HerinHentry** [comment]
Can close this issue. Thanks
