### ISSUE TITLE
Services Page _ The heights of the Grid are not exactly the same.

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#8]
Hi, I found the link related to the jquery to match the height. Can you please give this a go?
The Legal Services Section and the Accounting Services section grid height should be the same.
http://www.responsivegridsystem.com/playground/

**Comment by mr-bobz** [comment]
Refer what I have done in the home page. You can set same fixed height for both boxes
![4a07ce002d58f3e1](https://cloud.githubusercontent.com/assets/12365601/10864588/b3d64d98-8046-11e5-88e1-f64d70b83f89.jpg)
