### ISSUE TITLE
FAQ _ Duplicate / Test Page to be removed

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#80]
![image](https://github-cloud.s3.amazonaws.com/assets%2F15111528%2F10956821%2Fdb478e7c-83b2-11e5-972d-befa94fef68b.png)
us

**Comment by christosptr** [comment]
@HerinHentry Hi Herin I do not see the FAQs to be remove. Can you please double check for me and close this defect?

**Comment by HerinHentry** [comment]
@christosptr : The page has already been removed by mustan. Closing this issue.
