### ISSUE TITLE
Sign-up (join our E-list) is an external link. Is Jaws mentioning this as an external link?

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#81]
http://visitor.r20.constantcontact.com/d.jsp?llr=67lifhpab&p=oi&m=1115858153373&sit=lxc8balib&f=b119c4d1-f7ba-41c3-a67b-2afc56cca4fd

**Comment by HerinHentry** [comment]
I tested this with NVDA. It's read as "Opens in new window"
Code in place : title="Subscribe to TALA Newsletters (opens new window)"

**Comment by christosptr** [comment]
I test it also and it can stay as it is
