### ISSUE TITLE
Author name, Calendar date on the Posts to be removed

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#85]
![image](https://github-cloud.s3.amazonaws.com/assets%2F15111528%2F10957450%2F8f61a316-83b8-11e5-9ba7-9279c5a129be.png)

![image](https://github-cloud.s3.amazonaws.com/assets%2F15111528%2F10957464%2Facd89972-83b8-11e5-87ff-898a8f64a37d.png)

**Comment by HerinHentry** [comment]
@anmolpatel These posts are created not as pages. These are posts, and are added to the page with Cat list. These info do not match the colour contrast requirement as well. So, its important to remove it.

**Comment by anmolpatel** [comment]
added CSS to hide it.
it is in Custom CSS

**Comment by HerinHentry** [comment]
Excellent! Thank you. Closing issue
