### ISSUE TITLE
Links pointing to TALA current live website.

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#86]
Page : http://talarts.knowbility.org/643/

Visit our Dallas Week Events Page to learn more and register still links to Live website.But, this is a past event whose registration has closed. Instead should we use the word (Registration closed) inside this page and remove the link?

**Comment by anoopm7** [comment]
Is this still an issue? I see Herin you have already updated the text. Please advice.

**Comment by christosptr** [comment]
@anmolpatel I have fixed this as well closing issue
