### ISSUE TITLE
Post URLs are not consistent

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#88]
Few posts have the URLs as post name and few have the id. Can you please check?

http://talarts.knowbility.org/the-austin-chapter-of-the-texas-society-of-cpas-presents-nonprofit-financial-class/
http://talarts.knowbility.org/october-7-estate-planning-for-austin-artists/
http://talarts.knowbility.org/643/

@christosptr : Do we need to include the id/post? I think Title is better as its announced by screen reader.

**Comment by anoopm7** [comment]
Currently this setting is already configured to postname in wordpress settings. The default setting is ID, which is no longer used. For the URL http://talarts.knowbility.org/643/ I have updated this manually.

**Comment by anoopm7** [comment]
Having post names helps with SEO and postnames are easier to bookmark/remember.

**Comment by HerinHentry** [comment]
Excellent!

Oct 1, 2015Nov 1, 2015 :  http://talarts.knowbility.org/october-estate-planning-for-artists/
28.TALA Dallas Week :  http://talarts.knowbility.org/tala-dallas-week/
29.The Austin Chapter of the Texas Society of CPAs Presents: Nonprofit Financial Class :  http://talarts.knowbility.org/the-austin-chapter-of-the-texas-society-of-cpas-presents-nonprofit-financial-class/
30.October 7: Estate Planning for Austin Artists :  http://talarts.knowbility.org/october-7-estate-planning-for-austin-artists/
31.October: Estate Planning for Artists :  http://talarts.knowbility.org/october-estate-planning-for-artists/

Issue can be closed.
