### ISSUE TITLE
Event Posts should be child pages of Event page & not home page

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#89]
![image](https://cloud.githubusercontent.com/assets/15111528/10958946/5dff99ea-83c7-11e5-96ce-12e346b3cca8.png)

@anoopm7 : Can you please see the settings? 
@mr-bobz : Do you know of any quick fixes for this?

This applies to all the 4 posts in the Event page.

**Comment by anmolpatel** [comment]
Now it works correctly, 
all events are child pages for Events
<img width="1029" alt="screen shot 2015-11-11 at 6 01 09 pm" src="https://cloud.githubusercontent.com/assets/4068650/11085776/51667f10-889e-11e5-8cb9-1eb8c765cc14.png">

**Comment by HerinHentry** [comment]
Great work! Thank you. Closing the issue.
