### ISSUE TITLE
Title of the Home Page

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#9]
The current Title shows 
TALA | Home | Texas Accountants and Lawyers for the Arts
We want the title to be
"Texas Accountants and Lawyers for the Arts (TALA)"

Even the Services page Title is currently displayed as "Services | TALA | Home". Please change the page title in HTML.

**Comment by HerinHentry** [comment]
The current Title is repeated
Texas Accountants and Lawyers for the Arts (TALA) | Texas Accountants and Lawyers for the Arts

**Comment by mr-bobz** [comment]
Fixed. Title is now automatically generated and would be in following format
<page title> - Texas Accountants and Lawyers for the Arts (TALA)

eg: 
Home - Texas Accountants and Lawyers for the Arts (TALA)
About Us - Texas Accountants and Lawyers for the Arts (TALA)
