### ISSUE TITLE
Formatting issue Do I Qualify ? & membership page

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#91]
http://talarts.knowbility.org/services/do-i-qualify/
http://talarts.knowbility.org/services/membership/

As all the other pages have changed to one column, icons are not used anymore, we might need to change this to no icons page too.. The icons are occupying a lot more white space.
Please raise this issue in the next call and let's decide.

**Comment by HerinHentry** [comment]
Agreed at the call that this icons can be removed.

**Comment by HerinHentry** [comment]
@anoopm7 Can you please also check the extra spacing in the do-i-qualify page?
![image](https://cloud.githubusercontent.com/assets/15111528/10967556/5ad85f98-840f-11e5-91ab-62f81974f083.png)

Also, membership page can be made into single column page as screen reader focus has issues.
http://talarts.knowbility.org/services/membership/

**Comment by anmolpatel** [comment]
<img width="1090" alt="screen shot 2015-11-11 at 5 58 32 pm" src="https://cloud.githubusercontent.com/assets/4068650/11085735/ebb0a38a-889d-11e5-8c77-073219b921df.png">

this is the new layout, Formatting looks good,
not sure if there are any other issues

**Comment by HerinHentry** [comment]
This issue was fixed earlier. Can be closed.
