### ISSUE TITLE
Publications page _ The word icons need to be of same size

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#92]
http://talarts.knowbility.org/services/publications/

**Comment by HerinHentry** [comment]
@anoopm7 : The icons that are selected are two different icons. word_icon-300x300.png & 150 by 150 it seems. Can you please change it to one?
I think I accidentally changed this.

**Comment by mr-bobz** [comment]
Our theme already supports icon for these, better to use it
http://mtomas.com/389/tiny-forge-framework-child-themes-comprehensive-guide#Using-icon-webfont-to-style-links-to-PDF-and-other-documents

**Comment by mr-bobz** [comment]
I have enabled auto icon for attachments. Remove your icons. Also note that first link points to an image, not the doc file.

**Comment by mr-bobz** [comment]
Done the changes, pls recheck now, thanks

**Comment by HerinHentry** [comment]
Fixed, Issue can be closed.
