### ISSUE TITLE
Tag missing _ Parsing error on Volunteers page

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#93]
<...div id="page"> <...div id="left"> <...div class="po...</div> 
http://talarts.knowbility.org/support/volunteer/

**Comment by anmolpatel** [comment]
cannot replicate this issue

**Comment by HerinHentry** [comment]
No Duplicate IDs now.Parsing error now.
![image](https://cloud.githubusercontent.com/assets/15111528/11089835/2d28c158-88c1-11e5-8461-14ebfc03b0df.png)
