### ISSUE TITLE
duplicate id found on donate page

### ISSUE THREAD

**Issue by christosptr** [mr-bobz/talarts#95]

**Comment by anmolpatel** [comment]
@christosptr, which ID was it ?

**Comment by HerinHentry** [comment]
![image](https://cloud.githubusercontent.com/assets/15111528/10967849/95b2f28e-8411-11e5-97d4-692ecdb9b5b3.png)

![image](https://cloud.githubusercontent.com/assets/15111528/10967853/a22f14a2-8411-11e5-9aff-95fd07a88549.png)

![image](https://cloud.githubusercontent.com/assets/15111528/10967865/b0ba212e-8411-11e5-808c-a39f4be77532.png)

**Comment by christosptr** [comment]
thanks herin

Cheers Christos
Send from my mobile device

**Comment by anmolpatel** [comment]
Those cannot be changed as they all represent the same thing in the form structure
donate_user_amount --> is for the radio buttons
donation_header --> is for the legend in each section
errror_message --> shows up "This is a required field"

**Comment by HerinHentry** [comment]
I had a look at them. They fit into requirement.  This issue can be closed.

Sent from my phone

<div>-------- Original message --------</div><div>From: Anmol notifications@github.com </div><div>Date:08/11/2015  10:23 AM  (GMT+10:00) </div><div>To: mr-bobz/talarts talarts@noreply.github.com </div><div>Cc: HerinHentry herinnisha@gmail.com </div><div>Subject: Re: [talarts] duplicate id found on donate page (#95) </div><div>
</div>Those cannot be changed as they all represent the same thing in the form structure
donate_user_amount --> is for the radio buttons
donation_header --> is for the legend in each section
errror_message --> shows up "This is a required field"

**Comment by christosptr** [comment]
Closing as per comment above
