### ISSUE TITLE
Donate page: Usability with the donations table

### ISSUE THREAD

**Issue by christosptr** [mr-bobz/talarts#96]
The radio button when selecting donation starts from $100 to $5000
While the table start with 5,000 to 100 dollars

Change the table to also start with 100 dollars and increase as you move each row to match the radionbutton order

**Comment by anmolpatel** [comment]
Someone has already fixed the issue, please re-check and close the issue 
Thanks to whoever fixed it

**Comment by christosptr** [comment]
@anmolpatel I did sorry forgot to close the defect
