### ISSUE TITLE
Home page need to change h3 to h2

### ISSUE THREAD

**Issue by christosptr** [mr-bobz/talarts#98]
Mission Statement
and 
Do I Qualify for TALA Assistance?

Have H3 and need to change to h2

I change all pages and this is the only one I can not figure out where to do it.
When I go in read more about the Mission Statement the Mission statement is in h2

**Comment by christosptr** [comment]
@HerinHentry did you say you created this page?

**Comment by HerinHentry** [comment]
@christosptr : The structure looks good now for Home Page. I will check other pages later on,
![image](https://cloud.githubusercontent.com/assets/15111528/10967747/d14b3c08-8410-11e5-96d5-44bff06055c0.png)

**Comment by mr-bobz** [comment]
Done

**Comment by christosptr** [comment]
I also fixed the issue on the FAQs. This now looks good. closing defect
